#! /usr/bin/env python

from netmiko import ConnectHandler

def ez_cisco(hostname, show_command, username='ntc', password='ntc123'):
    platform = "cisco_ios"
    device = ConnectHandler(ip=hostname, username=username, password=password, device_type=platform)

    output = device.send_command(show_command)
    return output

response = ez_cisco('csr1', 'show version')
print(f"This is the show version output:\n\n{response}")

response = ez_cisco('csr2', 'show ip int brief')
print(f"This is the show interface output:\n\n{response}")

response = ez_cisco('csr3', 'show run | inc snmp')
print(f"This is the show running config for snmp output:\n\n{response}")
